/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as MarriageRouteImport } from './routes/marriage'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarriageIndexRouteImport } from './routes/marriage.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as UIdRouteImport } from './routes/u.$id'
import { Route as MarriageEditRouteImport } from './routes/marriage.edit'
import { Route as AuthNativeCallbackRouteImport } from './routes/auth_.native-callback'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AdminVideosRouteImport } from './routes/admin.videos'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSecurityRouteImport } from './routes/admin.security'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminPostsRouteImport } from './routes/admin.posts'
import { Route as AdminPhotosRouteImport } from './routes/admin.photos'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminModerationRouteImport } from './routes/admin.moderation'
import { Route as AdminMarriageRouteImport } from './routes/admin.marriage'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminCommentsRouteImport } from './routes/admin.comments'
import { Route as AdminChatRouteImport } from './routes/admin.chat'
import { Route as DotwellKnownAssetlinksDotjsonRouteImport } from './routes/[.]well-known.assetlinks[.]json'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'

const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MarriageRoute = MarriageRouteImport.update({
  id: '/marriage',
  path: '/marriage',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarriageIndexRoute = MarriageIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarriageRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const UIdRoute = UIdRouteImport.update({
  id: '/u/$id',
  path: '/u/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MarriageEditRoute = MarriageEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => MarriageRoute,
} as any)
const AuthNativeCallbackRoute = AuthNativeCallbackRouteImport.update({
  id: '/auth_/native-callback',
  path: '/auth/native-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AdminVideosRoute = AdminVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsRoute = AdminPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPhotosRoute = AdminPhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModerationRoute = AdminModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarriageRoute = AdminMarriageRouteImport.update({
  id: '/marriage',
  path: '/marriage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommentsRoute = AdminCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChatRoute = AdminChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AdminRoute,
} as any)
const DotwellKnownAssetlinksDotjsonRoute =
  DotwellKnownAssetlinksDotjsonRouteImport.update({
    id: '/.well-known/assetlinks.json',
    path: '/.well-known/assetlinks.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/marriage': typeof MarriageRouteWithChildren
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/upload': typeof UploadRoute
  '/videos': typeof VideosRoute
  '/.well-known/assetlinks.json': typeof DotwellKnownAssetlinksDotjsonRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/marriage': typeof AdminMarriageRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/photos': typeof AdminPhotosRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/videos': typeof AdminVideosRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/native-callback': typeof AuthNativeCallbackRoute
  '/marriage/edit': typeof MarriageEditRoute
  '/u/$id': typeof UIdRoute
  '/admin/': typeof AdminIndexRoute
  '/marriage/': typeof MarriageIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/upload': typeof UploadRoute
  '/videos': typeof VideosRoute
  '/.well-known/assetlinks.json': typeof DotwellKnownAssetlinksDotjsonRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/marriage': typeof AdminMarriageRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/photos': typeof AdminPhotosRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/videos': typeof AdminVideosRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/native-callback': typeof AuthNativeCallbackRoute
  '/marriage/edit': typeof MarriageEditRoute
  '/u/$id': typeof UIdRoute
  '/admin': typeof AdminIndexRoute
  '/marriage': typeof MarriageIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/marriage': typeof MarriageRouteWithChildren
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/upload': typeof UploadRoute
  '/videos': typeof VideosRoute
  '/.well-known/assetlinks.json': typeof DotwellKnownAssetlinksDotjsonRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/marriage': typeof AdminMarriageRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/photos': typeof AdminPhotosRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/videos': typeof AdminVideosRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth_/native-callback': typeof AuthNativeCallbackRoute
  '/marriage/edit': typeof MarriageEditRoute
  '/u/$id': typeof UIdRoute
  '/admin/': typeof AdminIndexRoute
  '/marriage/': typeof MarriageIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/marriage'
    | '/messages'
    | '/notifications'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/search'
    | '/sitemap.xml'
    | '/terms'
    | '/upload'
    | '/videos'
    | '/.well-known/assetlinks.json'
    | '/admin/chat'
    | '/admin/comments'
    | '/admin/login'
    | '/admin/marriage'
    | '/admin/moderation'
    | '/admin/notifications'
    | '/admin/photos'
    | '/admin/posts'
    | '/admin/reports'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/videos'
    | '/auth/callback'
    | '/auth/native-callback'
    | '/marriage/edit'
    | '/u/$id'
    | '/admin/'
    | '/marriage/'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/messages'
    | '/notifications'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/search'
    | '/sitemap.xml'
    | '/terms'
    | '/upload'
    | '/videos'
    | '/.well-known/assetlinks.json'
    | '/admin/chat'
    | '/admin/comments'
    | '/admin/login'
    | '/admin/marriage'
    | '/admin/moderation'
    | '/admin/notifications'
    | '/admin/photos'
    | '/admin/posts'
    | '/admin/reports'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/videos'
    | '/auth/callback'
    | '/auth/native-callback'
    | '/marriage/edit'
    | '/u/$id'
    | '/admin'
    | '/marriage'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/marriage'
    | '/messages'
    | '/notifications'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/search'
    | '/sitemap.xml'
    | '/terms'
    | '/upload'
    | '/videos'
    | '/.well-known/assetlinks.json'
    | '/admin/chat'
    | '/admin/comments'
    | '/admin/login'
    | '/admin/marriage'
    | '/admin/moderation'
    | '/admin/notifications'
    | '/admin/photos'
    | '/admin/posts'
    | '/admin/reports'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/videos'
    | '/auth/callback'
    | '/auth_/native-callback'
    | '/marriage/edit'
    | '/u/$id'
    | '/admin/'
    | '/marriage/'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  MarriageRoute: typeof MarriageRouteWithChildren
  MessagesRoute: typeof MessagesRoute
  NotificationsRoute: typeof NotificationsRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  UploadRoute: typeof UploadRoute
  VideosRoute: typeof VideosRoute
  DotwellKnownAssetlinksDotjsonRoute: typeof DotwellKnownAssetlinksDotjsonRoute
  AuthNativeCallbackRoute: typeof AuthNativeCallbackRoute
  UIdRoute: typeof UIdRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marriage': {
      id: '/marriage'
      path: '/marriage'
      fullPath: '/marriage'
      preLoaderRoute: typeof MarriageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marriage/': {
      id: '/marriage/'
      path: '/'
      fullPath: '/marriage/'
      preLoaderRoute: typeof MarriageIndexRouteImport
      parentRoute: typeof MarriageRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/u/$id': {
      id: '/u/$id'
      path: '/u/$id'
      fullPath: '/u/$id'
      preLoaderRoute: typeof UIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marriage/edit': {
      id: '/marriage/edit'
      path: '/edit'
      fullPath: '/marriage/edit'
      preLoaderRoute: typeof MarriageEditRouteImport
      parentRoute: typeof MarriageRoute
    }
    '/auth_/native-callback': {
      id: '/auth_/native-callback'
      path: '/auth/native-callback'
      fullPath: '/auth/native-callback'
      preLoaderRoute: typeof AuthNativeCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/videos': {
      id: '/admin/videos'
      path: '/videos'
      fullPath: '/admin/videos'
      preLoaderRoute: typeof AdminVideosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/security': {
      id: '/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts': {
      id: '/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/photos': {
      id: '/admin/photos'
      path: '/photos'
      fullPath: '/admin/photos'
      preLoaderRoute: typeof AdminPhotosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/moderation': {
      id: '/admin/moderation'
      path: '/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AdminModerationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marriage': {
      id: '/admin/marriage'
      path: '/marriage'
      fullPath: '/admin/marriage'
      preLoaderRoute: typeof AdminMarriageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/comments': {
      id: '/admin/comments'
      path: '/comments'
      fullPath: '/admin/comments'
      preLoaderRoute: typeof AdminCommentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/chat': {
      id: '/admin/chat'
      path: '/chat'
      fullPath: '/admin/chat'
      preLoaderRoute: typeof AdminChatRouteImport
      parentRoute: typeof AdminRoute
    }
    '/.well-known/assetlinks.json': {
      id: '/.well-known/assetlinks.json'
      path: '/.well-known/assetlinks.json'
      fullPath: '/.well-known/assetlinks.json'
      preLoaderRoute: typeof DotwellKnownAssetlinksDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminChatRoute: typeof AdminChatRoute
  AdminCommentsRoute: typeof AdminCommentsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMarriageRoute: typeof AdminMarriageRoute
  AdminModerationRoute: typeof AdminModerationRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPhotosRoute: typeof AdminPhotosRoute
  AdminPostsRoute: typeof AdminPostsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSecurityRoute: typeof AdminSecurityRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVideosRoute: typeof AdminVideosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminChatRoute: AdminChatRoute,
  AdminCommentsRoute: AdminCommentsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMarriageRoute: AdminMarriageRoute,
  AdminModerationRoute: AdminModerationRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPhotosRoute: AdminPhotosRoute,
  AdminPostsRoute: AdminPostsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSecurityRoute: AdminSecurityRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVideosRoute: AdminVideosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface MarriageRouteChildren {
  MarriageEditRoute: typeof MarriageEditRoute
  MarriageIndexRoute: typeof MarriageIndexRoute
}

const MarriageRouteChildren: MarriageRouteChildren = {
  MarriageEditRoute: MarriageEditRoute,
  MarriageIndexRoute: MarriageIndexRoute,
}

const MarriageRouteWithChildren = MarriageRoute._addFileChildren(
  MarriageRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  MarriageRoute: MarriageRouteWithChildren,
  MessagesRoute: MessagesRoute,
  NotificationsRoute: NotificationsRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  UploadRoute: UploadRoute,
  VideosRoute: VideosRoute,
  DotwellKnownAssetlinksDotjsonRoute: DotwellKnownAssetlinksDotjsonRoute,
  AuthNativeCallbackRoute: AuthNativeCallbackRoute,
  UIdRoute: UIdRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
