/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as MarriageRouteImport } from './routes/marriage'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarriageIndexRouteImport } from './routes/marriage.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as UIdRouteImport } from './routes/u.$id'
import { Route as MarriageEditRouteImport } from './routes/marriage.edit'
import { Route as AdminLoginRouteImport } from './routes/admin.login'

const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MarriageRoute = MarriageRouteImport.update({
  id: '/marriage',
  path: '/marriage',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarriageIndexRoute = MarriageIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarriageRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const UIdRoute = UIdRouteImport.update({
  id: '/u/$id',
  path: '/u/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MarriageEditRoute = MarriageEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => MarriageRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/marriage': typeof MarriageRouteWithChildren
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/upload': typeof UploadRoute
  '/videos': typeof VideosRoute
  '/admin/login': typeof AdminLoginRoute
  '/marriage/edit': typeof MarriageEditRoute
  '/u/$id': typeof UIdRoute
  '/admin/': typeof AdminIndexRoute
  '/marriage/': typeof MarriageIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/upload': typeof UploadRoute
  '/videos': typeof VideosRoute
  '/admin/login': typeof AdminLoginRoute
  '/marriage/edit': typeof MarriageEditRoute
  '/u/$id': typeof UIdRoute
  '/admin': typeof AdminIndexRoute
  '/marriage': typeof MarriageIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/marriage': typeof MarriageRouteWithChildren
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/upload': typeof UploadRoute
  '/videos': typeof VideosRoute
  '/admin/login': typeof AdminLoginRoute
  '/marriage/edit': typeof MarriageEditRoute
  '/u/$id': typeof UIdRoute
  '/admin/': typeof AdminIndexRoute
  '/marriage/': typeof MarriageIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/marriage'
    | '/messages'
    | '/notifications'
    | '/profile'
    | '/search'
    | '/terms'
    | '/upload'
    | '/videos'
    | '/admin/login'
    | '/marriage/edit'
    | '/u/$id'
    | '/admin/'
    | '/marriage/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/messages'
    | '/notifications'
    | '/profile'
    | '/search'
    | '/terms'
    | '/upload'
    | '/videos'
    | '/admin/login'
    | '/marriage/edit'
    | '/u/$id'
    | '/admin'
    | '/marriage'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/marriage'
    | '/messages'
    | '/notifications'
    | '/profile'
    | '/search'
    | '/terms'
    | '/upload'
    | '/videos'
    | '/admin/login'
    | '/marriage/edit'
    | '/u/$id'
    | '/admin/'
    | '/marriage/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  MarriageRoute: typeof MarriageRouteWithChildren
  MessagesRoute: typeof MessagesRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  TermsRoute: typeof TermsRoute
  UploadRoute: typeof UploadRoute
  VideosRoute: typeof VideosRoute
  UIdRoute: typeof UIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marriage': {
      id: '/marriage'
      path: '/marriage'
      fullPath: '/marriage'
      preLoaderRoute: typeof MarriageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marriage/': {
      id: '/marriage/'
      path: '/'
      fullPath: '/marriage/'
      preLoaderRoute: typeof MarriageIndexRouteImport
      parentRoute: typeof MarriageRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/u/$id': {
      id: '/u/$id'
      path: '/u/$id'
      fullPath: '/u/$id'
      preLoaderRoute: typeof UIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marriage/edit': {
      id: '/marriage/edit'
      path: '/edit'
      fullPath: '/marriage/edit'
      preLoaderRoute: typeof MarriageEditRouteImport
      parentRoute: typeof MarriageRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MarriageRouteChildren {
  MarriageEditRoute: typeof MarriageEditRoute
  MarriageIndexRoute: typeof MarriageIndexRoute
}

const MarriageRouteChildren: MarriageRouteChildren = {
  MarriageEditRoute: MarriageEditRoute,
  MarriageIndexRoute: MarriageIndexRoute,
}

const MarriageRouteWithChildren = MarriageRoute._addFileChildren(
  MarriageRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  MarriageRoute: MarriageRouteWithChildren,
  MessagesRoute: MessagesRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  TermsRoute: TermsRoute,
  UploadRoute: UploadRoute,
  VideosRoute: VideosRoute,
  UIdRoute: UIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
