// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { supabase } from './client'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    let token: string | undefined;
    try {
      // Protect RPCs from hanging if getSession() stalls. Race it against a
      // short timeout so middleware returns quickly even if auth storage is
      // slow or blocked (e.g. in constrained WebViews).
      const getSessionPromise = supabase.auth.getSession();
      const res = await Promise.race([
        getSessionPromise,
        new Promise((_, reject) => setTimeout(() => reject(new Error('getSession timeout')), 2500)),
      ]);
      // supabase.auth.getSession() resolves to { data, error }
      const data = (res as any)?.data;
      token = data?.session?.access_token;
    } catch (e) {
      // Don't block RPCs if session read fails — proceed without Authorization header.
      // Log for diagnostics.
      // eslint-disable-next-line no-console
      console.warn('[attachSupabaseAuth] getSession failed:', e);
      token = undefined;
    }

    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    })
  },
)
